FROM python:3.11-slim

WORKDIR /app
COPY requirements-migrations.txt ./
RUN pip install --no-cache-dir -r requirements-migrations.txt
COPY alembic.ini ./
COPY alembic/ ./alembic/

RUN useradd --system --uid 1000 migration
USER migration
CMD ["alembic", "upgrade", "head"]
